# Generated by Django 4.1 on 2022-08-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
    ]
